-- Ejecuta todo este script en la sección "SQL Editor" de tu panel de Supabase.
-- ATENCIÓN: Este script borrará los datos antiguos para crear la nueva estructura.

DROP TABLE IF EXISTS viajes_colaboradores CASCADE;
DROP TABLE IF EXISTS viajes CASCADE;
DROP TABLE IF EXISTS alojamientos CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

-- Creará las tablas necesarias para soportar usuarios, viajes, alojamientos e itinerarios.

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    rol TEXT DEFAULT 'user', -- 'user' o 'admin'
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE alojamientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creador_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    ubicacion TEXT NOT NULL,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    tipo TEXT DEFAULT 'Apartamento',
    precio_noche DOUBLE PRECISION NOT NULL,
    puntuacion INTEGER DEFAULT 3,
    resena TEXT DEFAULT '',
    repetir INTEGER DEFAULT 1,
    url TEXT DEFAULT '',
    plataforma TEXT DEFAULT '',
    notas TEXT DEFAULT '',
    color TEXT DEFAULT '#667eea',
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE viajes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creador_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    codigo_compartido TEXT UNIQUE,
    nombre TEXT NOT NULL,
    origen TEXT NOT NULL,
    destino TEXT NOT NULL,
    lat_origen DOUBLE PRECISION,
    lon_origen DOUBLE PRECISION,
    lat_destino DOUBLE PRECISION,
    lon_destino DOUBLE PRECISION,
    distancia_km DOUBLE PRECISION NOT NULL,
    tiempo_min DOUBLE PRECISION,
    consumo_l100 DOUBLE PRECISION NOT NULL,
    precio_comb DOUBLE PRECISION NOT NULL,
    num_personas INTEGER NOT NULL,
    num_dias INTEGER NOT NULL,
    precio_reserva DOUBLE PRECISION NOT NULL,
    ppto_comida DOUBLE PRECISION NOT NULL,
    gasto_gasolina DOUBLE PRECISION NOT NULL,
    gasto_comida DOUBLE PRECISION NOT NULL,
    coste_total DOUBLE PRECISION NOT NULL,
    coste_persona DOUBLE PRECISION NOT NULL,
    fecha_ida TEXT DEFAULT '',
    fecha_vuelta TEXT DEFAULT '',
    estado TEXT DEFAULT 'Planificado',
    alojamiento_id BIGINT REFERENCES alojamientos(id) ON DELETE SET NULL,
    gastos_extra TEXT DEFAULT '[]',
    gasto_extras DOUBLE PRECISION DEFAULT 0,
    itinerario TEXT DEFAULT '{}', -- JSON con los planes por día
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE viajes_colaboradores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viaje_id BIGINT REFERENCES viajes(id) ON DELETE CASCADE,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    rol_viaje TEXT DEFAULT 'Colaborador', -- 'Creador', 'Colaborador'
    fecha_union TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(viaje_id, usuario_id)
);

-- DESACTIVAR RLS (Row Level Security) para permitir operaciones desde la app con la clave anónima
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE viajes DISABLE ROW LEVEL SECURITY;
ALTER TABLE alojamientos DISABLE ROW LEVEL SECURITY;
ALTER TABLE viajes_colaboradores DISABLE ROW LEVEL SECURITY;

